# This file was generated by GoReleaser. DO NOT EDIT.
class Dtags < Formula
  desc ""
  homepage "https://github.com/bskim45/dtags/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bskim45/dtags/releases/download/1.0.0/dtags_1.0.0_darwin_amd64.tar.gz"
    sha256 "f835127dd913c7e91b892127fde96c568c700405ed22ef50eb9d785fbcde78fc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bskim45/dtags/releases/download/1.0.0/dtags_1.0.0_linux_amd64.tar.gz"
      sha256 "95f828dbe260f662234250411e32ace94649bd0e58250d7a8a321140d1f19f10"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bskim45/dtags/releases/download/1.0.0/dtags_1.0.0_linux_arm64.tar.gz"
        sha256 "6ae108665b4304acdd9a7c54d16c33588384fae9806be4a7fe471c2fa54ff634"
      else
        url "https://github.com/bskim45/dtags/releases/download/1.0.0/dtags_1.0.0_linux_armv6.tar.gz"
        sha256 "331dbe05f9ce466478f38a69f4e86af27da0f494beeb682d1ab44fb17b304cde"
      end
    end
  end

  def install
    bin.install "dtags"
  end
end
